### ISSUE TITLE
参数值调用函数问题

### ISSUE THREAD

**Issue by yeghub** [neolee/pilot-student#1]
3-structure-2小结第二条：
定义好的函数可以随时被调用，送入具体的参数值，得到函数返回值，返回值可以用于赋值也可以用作参数值来调用其他函数；
最后一句话，”可以用作参数值来调用其他函数；”是不是应该改为：可以用作参数值被其他函数调用；”

**Comment by neolee** [comment]
你跑的好快啊 😀

这句话就是它本来的意思，不是你理解的意思。

函数的作用是用输入的参数值来计算返回值，所以一个函数调用完成之后就是一个值，这个值可以作为输入参数去调用另一个函数，比如下面的例子：

```python
def add(x, y):
    return x + y

print(add(3, 4))
```

函数调用 `add(3, 4)` 完成后它就是个值（`7`），然后这个值可以作为参数去调用另一个函数 `print()`。
